spring:
  application:
    name: bookABatterySERVICE4EUREKA
  
server:
  port: 7111
  
eureka:
  password: password
#LOCAL CONF  
  client: 
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

#PROD PWS CONF 
#  client:
#    serviceUrl:
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
#      
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
     defaultZone: http://02-eureka-server.cfapps.io/eureka/
  instance:
    hostname: 06-bookABatterySERVICE4EUREKA.cfapps.io
    leaseRenewalIntervalInSeconds: 5
    nonSecurePort: 80
  