spring:
  application:
    name: bookABatteryCLIENT_RIBBON_SERVICE

server:
  port: 7211

bookABatterySERVICE4EUREKA:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:7111,localhost:7113,localhost:7115
    ServerListRefreshInterval: 15000
